### ISSUE TITLE
Unhandled Exception: NoSuchMethodError

### ISSUE THREAD

**Issue by kamrancr7** [cloudwebrtc/flutter-webrtc-demo#50]
i download the server from [here](https://github.com/cloudwebrtc/flutter-webrtc-server) and starts it successfully but when i run application and click on P2P call sample then following exception occuring:

```
E/flutter ( 1602): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'closeCode' was called on null.
E/flutter ( 1602): Receiver: null
E/flutter ( 1602): Tried calling: closeCode
E/flutter ( 1602): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 1602): #1      SimpleWebSocket.connect (package:flutter_webrtc_demo/src/utils/websocket.dart:29:28)
E/flutter ( 1602): <asynchronous suspension>
E/flutter ( 1602): #2      Signaling.connect (package:flutter_webrtc_demo/src/call_sample/signaling.dart:292:19)
E/flutter ( 1602): #3      _CallSampleState._connect (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:50:45)
E/flutter ( 1602): #4      _CallSampleState.initState (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:32:5)
E/flutter ( 1602): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter ( 1602): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
```
i also change the following line in main.dart file:
```
//_serverAddress = keyValueStore.getString('server') ?? 'demo.cloudwebrtc.com';
      _serverAddress = keyValueStore.getString('server') ?? '192.168.x.xxx:8086';
```

**Comment by kamrancr7** [comment]
solved my issue with the help of this [https://github.com/cloudwebrtc/flutter-webrtc-demo/issues/45](url)
