### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by kbrmimbyl** [cloudwebrtc/flutter-webrtc-demo#7]
Just checking this out... I tried to install the apk on my Redmi Note 4, and the app crashes on launch with the following report:

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cloudwebrtc.flutterwebrtcdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.cloudwebrtc.flutterwebrtcdemo-1/lib/arm64, /data/app/com.cloudwebrtc.flutterwebrtcdemo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
	at java.lang.System.loadLibrary(System.java:1530)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:157)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:134)
	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5518)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6354)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)

```

Flutter doctor doesn't report any errors or warnings:

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/user/Projects/flutter-projects/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

```

**Comment by kbrmimbyl** [comment]
Okay, looks like this is an arm64/arm32 issue (good discussion at https://github.com/azihsoyn/flutter_mlkit/issues/36). I could generate a working apk using this command:
`$ flutter build apk --debug --target-platform android-arm64`
But I'm not worried that this won't work on all phones.... also how about iOS? I haven't tried yet.

**Comment by kbrmimbyl** [comment]
Thanks rostopira! So it won't affect iOS but will it affect some Android phones?

**Comment by kbrmimbyl** [comment]
Superb! Thanks for the clarification again!

**Comment by rostopira** [comment]
Happy new year

**Comment by kbrmimbyl** [comment]
Happy new year to you too!

**Comment by xenixcorp** [comment]
@rostopira @kbrmimbyl I tried your work around crash in 32 bit Android. Try download emulator [Nox](https://id.bignox.com/) and add:
```
ndk { abiFilters "armeabi-v7a" }
```

**Comment by rostopira** [comment]
@xenixcorp yes, obviously it crashes, because emulator requires x86_64 instead of armv7
And again, this has nothing to do with library, it's flutter issue

**Comment by kbrmimbyl** [comment]
Hey, with ndk { abiFilters "armeabi-v7a" } everything seems fine and the apk size is nearly half! Cool!
